'use client'

import { useEffect, useRef, useState, useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { useAppDispatch, useAppSelector } from '@/lib/redux/hooks'
import {
  addMessage,
  openModal,
  setStage,
  setUserAnswer,
  nextQuestion,
  setDailyCalories,
  setIsPaid,
} from '@/features/chatbot/chatbotSlice'
import { Header } from '@/components/layout/Header'
import { Flame, ArrowLeft, Send, Download, RefreshCw, CheckCircle2, Zap } from 'lucide-react'

// ── Questions ─────────────────────────────────────────────────────────────────
const BASIC_QUESTIONS = [
  { key: 'weight' as const,   text: 'What is your current weight? (e.g. 85 kg)' },
  { key: 'goal' as const,     text: 'What is your main goal? (lose weight, maintain, or gain muscle)' },
  { key: 'activity' as const, text: 'How active are you? (sedentary / lightly active / active / very active)' },
]

const PREMIUM_QUESTIONS = [
  { key: 'weight' as const,          text: 'What is your current weight? (e.g. 85 kg)' },
  { key: 'goal' as const,            text: 'What is your main goal? (lose weight, maintain, or gain muscle)' },
  { key: 'activity' as const,        text: 'How active are you? (sedentary / lightly active / active / very active)' },
  { key: 'dietPreferences' as const, text: 'Any diet preferences? (e.g. keto, vegan, Mediterranean — or type "none")' },
  { key: 'allergies' as const,       text: 'Any food allergies or intolerances? (e.g. lactose, gluten — or type "none")' },
]

// ── Calorie helper ────────────────────────────────────────────────────────────
function estimateCalories(weightStr = '80', activityStr = '') {
  const w = parseInt(weightStr) || 80
  const active = activityStr.toLowerCase().includes('active')
  return active ? w * 32 : w * 27
}

// ── Full plan builder ─────────────────────────────────────────────────────────
function buildPlan(answers: Record<string, string | undefined>): string {
  const cals = estimateCalories(answers.weight, answers.activity)
  const protein = Math.round((parseInt(answers.weight ?? '80') * 1.8))
  const carbs   = Math.round((cals * 0.4) / 4)
  const fat     = Math.round((cals * 0.3) / 9)

  return `🎉 Your Personalized 7-Day Weight Loss Plan
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 Daily Target: ${cals} kcal
🥩 Protein: ${protein}g  🌾 Carbs: ${carbs}g  🥑 Fat: ${fat}g

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📅 7-Day Meal Plan:

Day 1 – Fresh Start
  Breakfast: Greek yogurt + berries + chia (350 kcal)
  Lunch:     Grilled chicken salad + olive oil (480 kcal)
  Dinner:    Baked salmon + roasted veggies + quinoa (550 kcal)
  Snack:     Handful of almonds (180 kcal)

Day 2 – Plant Power
  Breakfast: Oatmeal + banana + walnuts (380 kcal)
  Lunch:     Lentil soup + whole wheat bread (460 kcal)
  Dinner:    Tofu stir-fry + brown rice + broccoli (520 kcal)
  Snack:     Apple + peanut butter (200 kcal)

Day 3 – Lean & Clean
  Breakfast: Scrambled eggs + spinach + avocado toast (400 kcal)
  Lunch:     Turkey wrap + mixed greens (450 kcal)
  Dinner:    Grilled shrimp + zucchini noodles (490 kcal)
  Snack:     Protein shake (150 kcal)

Day 4 – Mediterranean
  Breakfast: Smoothie bowl + granola (370 kcal)
  Lunch:     Tuna salad + whole grain crackers (440 kcal)
  Dinner:    Lamb kofta + tabbouleh + hummus (560 kcal)
  Snack:     Dates + walnuts (160 kcal)

Day 5 – High Protein
  Breakfast: Cottage cheese + peaches + flaxseed (330 kcal)
  Lunch:     Chicken stir-fry + edamame + rice (510 kcal)
  Dinner:    Lean steak + sweet potato + salad (580 kcal)
  Snack:     Rice cakes + almond butter (170 kcal)

Day 6 – Light & Refreshing
  Breakfast: Green smoothie + boiled eggs (310 kcal)
  Lunch:     Grilled veggie panini on whole wheat (420 kcal)
  Dinner:    Baked cod + steamed asparagus + quinoa (470 kcal)
  Snack:     Mixed berries + mint (100 kcal)

Day 7 – Reward Day
  Breakfast: Whole wheat pancakes + honey + fruit (420 kcal)
  Lunch:     Chicken Caesar salad (480 kcal)
  Dinner:    Homemade veggie pizza (550 kcal)
  Snack:     Dark chocolate 85% + herbal tea (120 kcal)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 Top Tips:
  • Drink 2–3 L of water daily
  • Eat slowly — fullness takes 20 min
  • Sleep 7–8 h for optimal fat metabolism
  • Walk 8,000+ steps every day

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by FitlyAi 🔥 Personalized just for you.`
}

function downloadPlan(content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href = url
  a.download = 'FitlyAi-PersonalizedPlan.txt'
  a.click()
  URL.revokeObjectURL(url)
}

// ── Component ─────────────────────────────────────────────────────────────────
export default function ChatbotPage() {
  const dispatch = useAppDispatch()
  const router   = useRouter()

  const { stage, planType, messages, userAnswers, isPaid, questionStep, dailyCalories } =
    useAppSelector((s) => s.chatbot)
  const isAuthenticated = useAppSelector((s) => s.auth.isAuthenticated)
  const user            = useAppSelector((s) => s.auth.user)

  const [inputValue, setInputValue]   = useState('')
  const [isTyping, setIsTyping]       = useState(false)
  const [planContent, setPlanContent] = useState('')
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const inputRef       = useRef<HTMLInputElement>(null)

  // Guard: no planType → send home
  useEffect(() => {
    if (!planType) router.replace('/')
  }, [planType, router])

  // Guard: premium requires login
  useEffect(() => {
    if (planType === 'premium' && !isAuthenticated) router.replace('/')
  }, [planType, isAuthenticated, router])

  // Scroll to latest message
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, isTyping])

  // ── Boot greeting ───────────────────────────────────────────────────────────
  useEffect(() => {
    if (planType && messages.length === 0 && stage === 'questioning') {
      const firstName = user?.name?.split(' ')[0] ?? 'there'
      const greeting  = planType === 'premium'
        ? `Hey ${firstName}! 👋 I'm your FitlyAi coach. Let's build your personalized weight-loss plan — I just need to ask you a few quick questions. Ready? 🔥`
        : `Hey! 👋 Welcome to FitlyAi. I'll give you a quick calorie estimate to get you started. No account needed! Let's go.`

      setTimeout(() => {
        dispatch(addMessage({ role: 'assistant', content: greeting, type: 'text' }))
        const QUESTIONS = planType === 'basic' ? BASIC_QUESTIONS : PREMIUM_QUESTIONS
        setTimeout(() => {
          dispatch(addMessage({ role: 'assistant', content: QUESTIONS[0].text, type: 'text' }))
        }, 900)
      }, 400)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [planType])

  // ── Bot reply util ──────────────────────────────────────────────────────────
  const botReply = useCallback(
    (content: string, delay = 700, type: Message['type'] = 'text') => {
      setIsTyping(true)
      setTimeout(() => { setIsTyping(false); dispatch(addMessage({ role: 'assistant', content, type })) }, delay)
    },
    [dispatch]
  )

  // ── Handle user send ────────────────────────────────────────────────────────
  const handleSend = useCallback(() => {
    const text = inputValue.trim()
    if (!text || ['paywall', 'upgrade', 'processing'].includes(stage)) return

    dispatch(addMessage({ role: 'user', content: text, type: 'text' }))
    setInputValue('')

    const QUESTIONS = planType === 'basic' ? BASIC_QUESTIONS : PREMIUM_QUESTIONS
    const currentQ  = QUESTIONS[questionStep]
    if (currentQ) dispatch(setUserAnswer({ key: currentQ.key, value: text }))
    dispatch(nextQuestion())

    const nextStep = questionStep + 1

    if (nextStep < QUESTIONS.length) {
      botReply(QUESTIONS[nextStep].text, 800)
    } else {
      // ── All questions answered → insight ──────────────────────────────────
      dispatch(setStage('insight'))
      const answers = { ...userAnswers, [currentQ?.key ?? 'weight']: text }
      const cals    = estimateCalories(answers.weight ?? userAnswers.weight, answers.activity ?? userAnswers.activity)
      dispatch(setDailyCalories(cals))

      const goalLine = (answers.goal ?? userAnswers.goal ?? '').toLowerCase().includes('lose')
        ? 'With a small deficit, you could realistically lose 0.5–1 kg per week. 💪'
        : 'I can help you stay within this range to achieve your goal. 💪'

      botReply(
        `Based on your profile, your estimated daily calorie needs are around **${cals} kcal**. ${goalLine}`,
        1000
      )

      // ── Branch: basic → upgrade wall, premium → paywall ───────────────────
      if (planType === 'basic') {
        setTimeout(() => {
          dispatch(setStage('upgrade'))
          setIsTyping(true)
          setTimeout(() => {
            setIsTyping(false)
            dispatch(addMessage({
              role: 'assistant',
              content: `You've reached the limit of the free plan. To generate your full 7-day personalized meal plan and download it as a PDF, unlock Premium.`,
              type: 'upgrade',
            }))
          }, 900)
        }, 2800)
      } else {
        setTimeout(() => {
          dispatch(setStage('paywall'))
          setIsTyping(true)
          setTimeout(() => {
            setIsTyping(false)
            dispatch(addMessage({
              role: 'assistant',
              content: `I'm ready to generate your full personalized plan! This includes:\n• A complete **7-day meal plan**\n• Daily **calorie & macro breakdown**\n• Expert **tips & recommendations**\n• A **downloadable summary**`,
              type: 'paywall',
            }))
          }, 1200)
        }, 3000)
      }
    }
  }, [inputValue, stage, planType, questionStep, dispatch, botReply, userAnswers])

  // ── Payment handler ─────────────────────────────────────────────────────────
  const handlePayment = useCallback(() => {
    dispatch(setStage('processing'))
    dispatch(addMessage({ role: 'assistant', content: '✅ Payment confirmed! Perfect — generating your plan now...', type: 'text' }))
    setIsTyping(true)
    setTimeout(() => {
      const plan = buildPlan(userAnswers as Record<string, string>)
      setPlanContent(plan)
      setIsTyping(false)
      dispatch(setIsPaid(true))
      dispatch(setStage('complete'))
      dispatch(addMessage({ role: 'assistant', content: plan, type: 'plan' }))
      setTimeout(() => {
        dispatch(addMessage({
          role: 'assistant',
          content: `🎯 Your plan is ready! Need help with a specific day, meal swaps, or have questions? Just ask — I'm here all week! 💬`,
          type: 'upsell',
        }))
      }, 1500)
    }, 3000)
  }, [dispatch, userAnswers])

  const QUESTIONS = planType === 'basic' ? BASIC_QUESTIONS : PREMIUM_QUESTIONS
  const totalQ    = QUESTIONS.length
  const isInputDisabled = ['paywall', 'upgrade', 'processing'].includes(stage)

  if (!planType) return null

  return (
    <div className="flex h-screen flex-col bg-background">

      {/* ── Site Header ── */}
      <Header />
      <header className="flex shrink-0 items-center justify-between border-b border-border/40 bg-background/80 px-4 py-3 backdrop-blur-md sm:px-6">
        <div className="flex items-center gap-3">
          <button
            onClick={() => router.push('/')}
            className="flex h-8 w-8 items-center justify-center rounded-full bg-secondary text-muted-foreground transition-colors hover:bg-secondary/70 hover:text-foreground"
          >
            <ArrowLeft className="h-4 w-4" />
          </button>
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10">
              <Flame className="h-4 w-4 text-primary" />
            </div>
            <div>
              <p className="text-sm font-semibold text-foreground">FitlyAi Coach</p>
              <p className="flex items-center gap-1 text-xs text-green-500">
                <span className="inline-block h-1.5 w-1.5 rounded-full bg-green-500" />
                Online · {planType === 'premium' ? 'Premium' : 'Free'} mode
              </p>
            </div>
          </div>
        </div>

        {/* Plan badge */}
        {planType === 'premium' ? (
          <span className="inline-flex items-center gap-1.5 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
            <Zap className="h-3.5 w-3.5" /> Premium
          </span>
        ) : (
          <button
            onClick={() => dispatch(openModal())}
            className="inline-flex items-center gap-1.5 rounded-full border border-primary/30 bg-transparent px-3 py-1 text-xs font-semibold text-primary transition-colors hover:bg-primary/5"
          >
            <Zap className="h-3.5 w-3.5" /> Upgrade
          </button>
        )}
      </header>

      {/* ── Progress bar ── */}
      {stage === 'questioning' && (
        <div className="h-0.5 w-full bg-secondary">
          <div
            className="h-full bg-primary transition-all duration-500"
            style={{ width: `${Math.min((questionStep / totalQ) * 100, 100)}%` }}
          />
        </div>
      )}

      {/* ── Messages ── */}
      <div className="flex-1 overflow-y-auto px-4 py-6 sm:px-6">
        <div className="mx-auto max-w-2xl space-y-4">
          {messages.map((msg) => (
            <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>

              {msg.role === 'assistant' && (
                <div className="mr-2 mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10">
                  <Flame className="h-3.5 w-3.5 text-primary" />
                </div>
              )}

              <div className={`max-w-[82%] ${msg.role === 'user' ? 'order-1' : ''}`}>

                {/* ── UPGRADE wall ── */}
                {msg.type === 'upgrade' ? (
                  <div className="overflow-hidden rounded-2xl rounded-tl-sm border border-primary/20 bg-card shadow-sm">
                    <div className="bg-gradient-to-r from-primary/10 to-orange-500/10 px-5 py-3">
                      <p className="text-xs font-semibold uppercase tracking-wider text-primary">Free limit reached</p>
                    </div>
                    <div className="px-5 py-4">
                      <p className="text-sm leading-relaxed text-foreground">{msg.content}</p>
                      <ul className="mt-3 space-y-1.5">
                        {['Full 7-day meal plan', 'Calorie & macro breakdown', 'Downloadable PDF', 'Unlimited chat'].map((f) => (
                          <li key={f} className="flex items-center gap-2 text-sm text-muted-foreground">
                            <CheckCircle2 className="h-4 w-4 text-primary" /> {f}
                          </li>
                        ))}
                      </ul>
                      <div className="mt-4 rounded-xl bg-primary/5 p-3 text-center">
                        <p className="text-2xl font-extrabold text-foreground">9$ <span className="text-sm font-semibold">one-time</span></p>
                        <p className="text-xs text-muted-foreground">One-time · Instant access</p>
                      </div>
                      <button
                        onClick={() => dispatch(openModal())}
                        className="mt-4 flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground shadow-md shadow-primary/25 transition-all hover:brightness-110 active:scale-[0.98]"
                      >
                        <Zap className="h-4 w-4" /> Unlock Full Plan (9$)
                      </button>
                    </div>
                  </div>

                /* ── PAYWALL card ── */
                ) : msg.type === 'paywall' ? (
                  <div className="overflow-hidden rounded-2xl rounded-tl-sm border border-border bg-card shadow-sm">
                    <div className="bg-gradient-to-r from-primary/10 to-orange-500/10 px-5 py-3">
                      <p className="text-xs font-semibold uppercase tracking-wider text-primary">Your plan is ready</p>
                    </div>
                    <div className="px-5 py-4">
                      <p className="whitespace-pre-line text-sm leading-relaxed text-foreground">{msg.content}</p>
                      <div className="mt-4 rounded-xl bg-primary/5 p-4 text-center">
                        <p className="text-2xl font-extrabold text-foreground">9$ <span className="text-base font-semibold">one-time</span></p>
                        <p className="mt-0.5 text-xs text-muted-foreground">One-time · Instant access</p>
                      </div>
                      <button
                        onClick={handlePayment}
                        className="mt-4 flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/25 transition-all hover:brightness-110 active:scale-[0.98]"
                      >
                        ⚡ Generate My Plan (9$)
                      </button>
                    </div>
                  </div>

                /* ── PLAN card ── */
                ) : msg.type === 'plan' ? (
                  <div className="overflow-hidden rounded-2xl rounded-tl-sm border border-green-500/20 bg-card shadow-sm">
                    <div className="bg-gradient-to-r from-green-500/10 to-emerald-500/10 px-5 py-3">
                      <p className="text-xs font-semibold uppercase tracking-wider text-green-600">✅ Your Full Plan</p>
                    </div>
                    <div className="max-h-80 overflow-y-auto px-5 py-4">
                      <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-foreground">{msg.content}</pre>
                    </div>
                    <div className="border-t border-border px-5 py-3">
                      <button
                        onClick={() => downloadPlan(planContent)}
                        className="flex w-full items-center justify-center gap-2 rounded-lg bg-green-500 px-4 py-2 text-sm font-semibold text-white transition-all hover:bg-green-600 active:scale-[0.98]"
                      >
                        <Download className="h-4 w-4" /> Download Full Plan
                      </button>
                    </div>
                  </div>

                /* ── UPSELL card ── */
                ) : msg.type === 'upsell' ? (
                  <div className="overflow-hidden rounded-2xl rounded-tl-sm border border-orange-500/20 bg-card shadow-sm">
                    <div className="px-5 py-4">
                      <p className="text-sm leading-relaxed text-foreground">{msg.content}</p>
                      <div className="mt-3 flex flex-col gap-2 sm:flex-row">
                        <button className="flex-1 rounded-lg border border-primary/30 bg-primary/5 px-3 py-2 text-xs font-semibold text-primary transition-colors hover:bg-primary/10">
                          🔄 Yes, send weekly plans
                        </button>
                        <button className="flex-1 rounded-lg border border-border bg-secondary/50 px-3 py-2 text-xs font-semibold text-muted-foreground transition-colors hover:bg-secondary">
                          No thanks
                        </button>
                      </div>
                    </div>
                  </div>

                /* ── Standard bubble ── */
                ) : (
                  <div
                    className={`rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                      msg.role === 'user'
                        ? 'rounded-br-sm bg-primary text-primary-foreground'
                        : 'rounded-tl-sm bg-secondary text-foreground'
                    }`}
                  >
                    {msg.content.replace(/\*\*(.*?)\*\*/g, '$1')}
                  </div>
                )}
              </div>

              {msg.role === 'user' && (
                <div className="ml-2 mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/20 text-xs font-bold text-primary">
                  {user?.name?.charAt(0) ?? '?'}
                </div>
              )}
            </div>
          ))}

          {/* Typing indicator */}
          {isTyping && (
            <div className="flex items-start gap-2">
              <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10">
                <Flame className="h-3.5 w-3.5 text-primary" />
              </div>
              <div className="rounded-2xl rounded-tl-sm bg-secondary px-4 py-3">
                <div className="flex gap-1">
                  {[0, 1, 2].map((i) => (
                    <span
                      key={i}
                      className="inline-block h-2 w-2 rounded-full bg-muted-foreground/50 animate-bounce"
                      style={{ animationDelay: `${i * 0.15}s` }}
                    />
                  ))}
                </div>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>
      </div>

      {/* ── Input bar ── */}
      <div className="shrink-0 border-t border-border/40 bg-background/80 px-4 py-3 backdrop-blur-md sm:px-6">
        <div className="mx-auto max-w-2xl">
          <div className="flex items-center gap-3">
            <input
              ref={inputRef}
              type="text"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  if (stage === 'complete') {
                    handleFollowUp()
                  } else {
                    handleSend()
                  }
                }
              }}
              disabled={isInputDisabled}
              placeholder={
                isInputDisabled
                  ? stage === 'processing' ? 'Generating your plan...'
                  : stage === 'upgrade'    ? 'Upgrade to continue'
                  : 'Complete payment to continue'
                  : stage === 'complete'   ? 'Ask a follow-up question...'
                  : 'Type your answer...'
              }
              className="flex-1 rounded-xl border border-border bg-secondary/50 px-4 py-2.5 text-sm text-foreground placeholder-muted-foreground outline-none transition-colors focus:border-primary/50 focus:bg-background disabled:cursor-not-allowed disabled:opacity-50"
            />
            <button
              onClick={stage === 'complete' ? handleFollowUp : handleSend}
              disabled={isInputDisabled || !inputValue.trim()}
              className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-primary-foreground transition-all hover:brightness-110 active:scale-95 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {stage === 'processing'
                ? <RefreshCw className="h-4 w-4 animate-spin" />
                : <Send className="h-4 w-4" />}
            </button>
          </div>
          <p className="mt-2 text-center text-[10px] text-muted-foreground/50">
            FitlyAi · AI-powered · For informational purposes only
          </p>
        </div>
      </div>
    </div>
  )

  function handleFollowUp() {
    const text = inputValue.trim()
    if (!text) return
    dispatch(addMessage({ role: 'user', content: text, type: 'text' }))
    setInputValue('')
    botReply(
      `Great question! For your profile — ${userAnswers.weight ?? 'your weight'}, goal: ${userAnswers.goal ?? 'your goal'} — staying consistent with the plan is key. Feel free to ask about meal swaps, portions, or tips anytime! 💪`,
      900
    )
  }
}

// Needed for JSX type annotation inside the component
type Message = ReturnType<typeof useAppSelector> extends never ? never : {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: number
  type?: 'text' | 'plan' | 'paywall' | 'upgrade' | 'upsell'
}
